<<<<<<< HEAD
app = "gaming-gamers"
primary_region = "sin"

[env]
  NODE_ENV = "production"

[processes]
  app = "node index.js"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
=======
# fly.toml app configuration file generated for gaming-gamers on 2026-05-25T04:09:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gaming-gamers'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
>>>>>>> cd7d85d0f1e9da672464fde2697be767a27a3676
